App:
  Host: "0.0.0.0"
  Port: 18080
  AdminMain: "admin"
  SecretKey: "6oFChDc2tQhXlM8XSTqAnqJik4kkpU2v"   #16,24,32位字符串，分别对应AES-128，AES-192，AES-256 加密方法
  Captcha:
    Enable: true
    Type: "string" #audio：声音验证码，string：字符串验证码，math：数学验证码，chinese：中文验证码，如果配置错误或者为空则为数字验证码
  CS:
    Enable: true
    SignKey: "OKLJgorIE8iyaeNC"

Database:
  Mysql:
    Enable: true
    Host: ""
    Port: 3306
    DataName: ""
    UserName: ""
    Password: ""
    Charset: "utf8mb4"
    RedisCache: true #使用redis作为mysql的缓存驱动
  Redis:
    Enable: false
    Host: ""
    Port: 6379
    Password: ""

OpenAPI:
  QWeather: # 和风天气api
    Host: "https://devapi.qweather.com/v7"
    PrivateKEYS: # 账号列表,自动负载均衡
      - Name: "" # 账号名称
        Key: "" # 和风天气api的私钥
        Weight: 1 # 权重,默认为1,越大越优先使用